商品出品ページの作成準備
KosukeNogo/fleamarket_sample_kagawa-a pull request #13
Opened 2021-01-30 03:19 UTC by GotoUkyo

・items_controller.rbにnewアクションを設定
・items/new.html.hamlとitems/new.scssを作成
・items/new.scssを読み込むようapplication.scssで設定

2021-02-02 04:07 UTC, GotoUkyo commented
当方のブラウザでこのページを表示したものをスクロールしているGIF画像です。
https://gyazo.com/4c5139ef71bdad40ac7a2efa90fd87d6

2021-02-02 06:32 UTC, daisukekamakura commented
レビューおそくない申し訳ないです。
LGTMです。

2021-02-02 08:49 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。

コメントしておりますので、ご確認のほどよろしくお願いいたします。
また、修正後再度ご提出頂く際には、実際にブラウザ上でどのように表示されているか確認させて頂きたい為、Gyazoを用いてスクリーンショットを撮影して頂き、生成されるURLを併せてご提出下さい。

2021-02-02 08:49 UTC, yupimaru commented on app/assets/stylesheets/items/new.scss
> +}
```SCSS
:root{
  --white-color: white;
  --label-red: red;
  --new-border-color: rgb(206, 206, 206);
  --font-gray: rgb(156, 156, 156);
  --font-blue: dodgerblue;
}

@mixin label{
  color: var(--white-color);
  font-weight: bold;
  font-size: 12px;
  padding: 0 5px;
  margin: 35px 0 17px 0;
  border-radius: 3px;
}

@mixin btn{
  height: 50px;
  width: 360px;
  font-size: 17px;
  font-weight: bold;
  text-decoration: none;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 5px;
}

@mixin bar{
  width: 620px;
  height: 50px;
  font-size: 15px;
  padding-left: 15px;
  border: 1px solid var(--new-border-color);
  border-radius: 5px;
}
```

上記のような記述はファイルを切り分けましょう。
今の実装ですと、今後メンテンナンスをするときにどこで何を設定したかわかりにくくなります。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      .Image-space__detail 最大5枚までアップロードできます
```haml
.Image-space__detail 最大5枚までアップロードできます
```

必須機能では画像は1枚だけで大丈夫です。
追加実装に着手するタイミングでこちらの記述も合わせましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "レディース", "メンズ", "ベビー・キッズ", "インテリア・住まい・小物", "本・音楽・ゲーム", "おもちゃ・ホビー・グッズ", "コスメ・香水・美容", "家電・スマホ・カメラ", "スポーツ・レジャー", "ハンドメイド", "チケット", "自動車・オートバ
```haml
 = select_tag 'select', options_for_select(["選択してください", "レディース", "メンズ", "ベビー・キッズ", "インテリア・住まい・小物", "本・音楽・ゲーム", "おもちゃ・ホビー・グッズ", "コスメ・香水・美容", "家電・スマホ・カメラ", "スポーツ・レジャー", "ハンドメイド", "チケット", "自動車・オートバイ", "その他"]), class: "category-select"
```

23行目で`form_with`を用いているようですので、`f.select`を用いて記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "新品・未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"]), class: "state-select"
```haml
 = select_tag 'select', options_for_select(["選択してください", "新品・未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"]), class: "state-select"
```

23行目で`form_with`を用いているようですので、`f.select`を用いて記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "送料込み（出品者負担）", "着払い（購入者負担）"]), class: "burden-select"
```haml
= select_tag 'select', options_for_select(["選択してください", "送料込み（出品者負担）", "着払い（購入者負担）"]), class: "burden-select"
```

23行目で`form_with`を用いているようですので、`f.select`を用いて記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県"]), class: "sending-select"
```haml
= select_tag 'select', options_for_select(["選択してください", "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県"]), class: "sending-select"
```

23行目で`form_with`を用いているようですので、`f.select`を用いて記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "1〜2日で発送", "2〜3日で発送", "4〜7日で発送"]), class: "days-select"
```haml
= select_tag 'select', options_for_select(["選択してください", "1〜2日で発送", "2〜3日で発送", "4〜7日で発送"]), class: "days-select"
```

23行目で`form_with`を用いているようですので、`f.select`を用いて記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +          %input.Price__set--value__bar{type: "number", value: "0", min: "300", max: "9999999"}
```haml
%input.Price__set--value__bar{type: "number", value: "0", min: "300", max: "9999999"}
```

23行目で`form_with`を用いているようですので、inputタグを直書きせずに`f.~`の形で記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      %input.Detail__input{placeholder: "例）シャネル", "type": "text"}
```haml
%input.Detail__input{placeholder: "例）シャネル", "type": "text"}
```

23行目で`form_with`を用いているようですので、inputタグを直書きせずに`f.~`の形で記述しましょう。

2021-02-02 08:49 UTC, yupimaru commented on app/views/items/new.html.haml
> +      = form_with do |f|
```haml
= form_with do |f|
```

上記記述は23行目で正しいでしょうか？

2021-02-03 03:57 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      .Image-space__detail 最大5枚までアップロードできます
追加実装時に再度書かなくていいように、hamlとscssの該当部分をメモ付きでコメントアウト化しました。

2021-02-03 05:30 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      = form_with do |f|
記述を6行目に変更しました。

2021-02-03 05:32 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "レディース", "メンズ", "ベビー・キッズ", "インテリア・住まい・小物", "本・音楽・ゲーム", "おもちゃ・ホビー・グッズ", "コスメ・香水・美容", "家電・スマホ・カメラ", "スポーツ・レジャー", "ハンドメイド", "チケット", "自動車・オートバ
f.select〜の記述に変更しました。

2021-02-03 05:32 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "新品・未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"]), class: "state-select"
f.select〜の記述に変更しました。

2021-02-03 05:33 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "送料込み（出品者負担）", "着払い（購入者負担）"]), class: "burden-select"
f.select〜の記述に変更しました。

2021-02-03 05:33 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "北海道", "青森県", "岩手県", "宮城県", "秋田県", "山形県", "福島県", "茨城県", "栃木県", "群馬県", "埼玉県", "千葉県", "東京都", "神奈川県", "新潟県", "富山県"]), class: "sending-select"
f.select〜の記述に変更しました。

2021-02-03 05:33 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      = select_tag 'select', options_for_select(["選択してください", "1〜2日で発送", "2〜3日で発送", "4〜7日で発送"]), class: "days-select"
f.select〜の記述に変更しました。

2021-02-03 05:34 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +          %input.Price__set--value__bar{type: "number", value: "0", min: "300", max: "9999999"}
f.number_field〜の記述に変更しました。

2021-02-03 05:34 UTC, GotoUkyo commented on app/views/items/new.html.haml
> +      %input.Detail__input{placeholder: "例）シャネル", "type": "text"}
f.text_field〜の記述に変更しました。

2021-02-03 05:50 UTC, GotoUkyo commented on app/assets/stylesheets/items/new.scss
> +}
rootとmixinを_color-mixin.scssという名前のファイルに切り分けました。

2021-02-03 05:51 UTC, GotoUkyo commented
修正後のページを当方のブラウザで表示したものをスクロールしているGIF画像です。
https://gyazo.com/8bc748de98cba60b9433585564e9eef7

2021-02-03 05:55 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

今回の修正を持って**LGTM**とさせて頂きます。
商品出品ページのマークアップお疲れさまでした。

masterブランチへマージ後、次の実装へ進みましょう。
引き続き実装頑張っていきましょう。応援しております！

2021-02-03 10:11 UTC, GotoUkyo commented
レビューしてくださりありがとうございました！

2021-02-03 10:11 UTC, merged