マイページ画面
KosukeNogo/fleamarket_sample_kagawa-a pull request #26
Opened 2021-02-19 07:07 UTC by yamahata-hiroki

# what
マイページの実装
#why
ユーザーの情報確認のため

2021-02-19 07:29 UTC, daisukekamakura commented
お疲れ様です。LGTMです。
トレーナーのLGTMがもらえたらマージするのですが、その際にコンフリクトが起きるかもしれません。トレーナーに質問しながらするか、心配ならば明日一緒に行いましょう。

2021-02-20 07:04 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
コメントしましたので、ご確認をお願いいたします！

また、修正後再度ご提出頂く際には、実際の画面や機能ができているか確認させていただきたいので、
キャプチャ画像をご提出いただけますか？
ツールは**Gyazo**を用いて頂き、ツールによって生成されたURLをこのPRに貼っていただければ幸いです。
どうぞよろしくお願い致します！

2021-02-20 07:04 UTC, yupimaru commented on app/assets/stylesheets/user.scss
> +    background:rgb(255, 255, 255);
```SCSS
rgb(255, 255, 255)
```

上記色コードは繰り返し使用しているようですので、変数化して使用しましょう。

2021-02-20 07:43 UTC, goku-naoki commented
LGTMとさせて頂きます！
実装お疲れ様でした！

2021-02-20 08:34 UTC, merged